# Generated by Django 5.1.4 on 2025-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_complaint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
